In [14]:
# %matplotlib inline

Bit Error Rate (BER)

*  The Bit Error Rate (BER) is a measure of how many bits of data are incorrectly received compared to the total number of bits sent over a communication channel. It is expressed as a ratio or percentage.

*  The formula for calculating BER is:
  
*  BER = Number of Bit Errors / Total Number of Bits Sent


*  If you send 1,000 bits and 10 of those bits are received incorrectly, the BER would be:
*  BER = 10/1000 = 0.01 or 1%

Block Error Rate (BLER)
Definition:
The Block Error Rate (BLER) measures the number of blocks of data that are received incorrectly compared to the total number of blocks sent. A "block" typically refers to a group of bits that are transmitted together, often as part of a larger message.


- The formula for calculating BLER is:
 BLER = Number of Block Errors / Total Number of Blocks Sent



- If you send 100 blocks of data and 5 of those blocks are received incorrectly, the BLER would be:
BLER = 5/100 = 5%

In [3]:
import importlib
import AIsim_main2  # Ensure the module is imported

In [4]:
# Reload the module to reflect changes
importlib.reload(AIsim_main2)

from AIsim_main2 import sim_bersingle2, Transmitter

In [5]:
# Define the necessary variables before calling the function
dataset_folder = r"D:\Research\AIsensing\deeplearning\Database"
scenario = "O1_60"

NUM_UT = 1
NUM_BS = 1
NUM_UT_ANT = 1
NUM_BS_ANT = 16
NUM_BITS_PER_SYMBOL = 2
BATCH_SIZE = 128
showfigure = True
datapathbase = "data/"

eval_transceiver = Transmitter(
    channeldataset="deepmimo",
    channeltype="ofdm",
    scenario=scenario,
    dataset_folder=dataset_folder,
    direction="uplink",
    num_ut=NUM_UT,
    num_ut_ant=NUM_UT_ANT,
    num_bs=NUM_BS,
    num_bs_ant=NUM_BS_ANT,
    batch_size=BATCH_SIZE,
    fft_size=76,
    num_ofdm_symbols=14,
    num_bits_per_symbol=NUM_BITS_PER_SYMBOL,
    subcarrier_spacing=60e3,
    USE_LDPC=False,
    pilot_pattern="kronecker",
    guards=True,
    showfig=showfigure,
    savedata=True,
    outputpath=datapathbase,  # deepmimo_ofdm_
)
# # Now you can call the function
# print("running deepmimo dataset")
# bers, blers, BERs = sim_bersingle2(
#     channeldataset="deepmimo",
#     channeltype="ofdm",
#     NUM_BITS_PER_SYMBOL=2,
#     EBN0_DB_MIN=-5.0,
#     EBN0_DB_MAX=25.0,
#     BATCH_SIZE=128,
#     NUM_UT=1,
#     NUM_BS=1,
#     NUM_UT_ANT=1,
#     NUM_BS_ANT=16,
#     showfigure=True,  # or whatever value you want
#     datapathbase="data/",
#     dataset_folder=dataset_folder
# )

# # Add this line to display the figures
# import matplotlib.pyplot as plt

# plt.show()  # Ensure figures are displayed

Average energy per pilot symbol: 1.00
RG num_ofdm_symbols 14
RG ofdm_symbol_duration 1.7982456140350878e-05
512

Basestation 1

UE-BS Channels


Generating channels: 100%|██████████| 18100/18100 [00:02<00:00, 6254.36it/s]



BS-BS Channels


Generating channels: 100%|██████████| 1/1 [00:00<?, ?it/s]


dict_keys(['paths', 'LoS', 'location', 'distance', 'pathloss', 'channel'])
(18100, 3)
[242.42300415 297.17098999   2.        ]
1
dict_keys(['user', 'basestation', 'location'])
dict_keys(['paths', 'LoS', 'location', 'distance', 'pathloss', 'channel'])
18100
(18100, 1, 16, 10)
(18100, 1, 16, 10)
[[[-3.40252654e-06-1.42072656e-06j  1.81741018e-06+2.55279360e-06j
   -2.07117159e-06+1.63894288e-06j -1.15924456e-06-4.15754414e-07j
    1.61744200e-08+6.18089018e-07j -4.61281388e-07-3.27500629e-07j
    3.21317053e-08+1.42540202e-07j  2.89082109e-08-1.40979708e-07j
    7.96548427e-09+4.98924386e-08j  0.00000000e+00+0.00000000e+00j]
  [-2.97919746e-06-2.17256388e-06j  2.91234210e-06+1.15671912e-06j
   -2.39480664e-06+1.11390580e-06j -1.19963624e-06+2.78518655e-07j
   -4.32637762e-07-4.41724154e-07j  5.60680348e-07-7.53309948e-08j
    6.10191151e-08-1.32766047e-07j -1.08757888e-07+9.42479943e-08j
    1.72580816e-09-5.04948119e-08j  0.00000000e+00+0.00000000e+00j]
  [-2.39273436e-06-2.80543645e-06

Generating channels: 100%|██████████| 18100/18100 [00:02<00:00, 8452.43it/s]



BS-BS Channels


Generating channels: 100%|██████████| 1/1 [00:00<00:00, 60.62it/s]


dict_keys(['paths', 'LoS', 'location', 'distance', 'pathloss', 'channel'])
(18100, 3)
[242.42300415 297.17098999   2.        ]
1
dict_keys(['user', 'basestation', 'location'])
dict_keys(['paths', 'LoS', 'location', 'distance', 'pathloss', 'channel'])
18100
(18100, 1, 16, 10)
(18100, 1, 16, 10)
[[[-3.40252654e-06-1.42072656e-06j  1.81741018e-06+2.55279360e-06j
   -2.07117159e-06+1.63894288e-06j -1.15924456e-06-4.15754414e-07j
    1.61744200e-08+6.18089018e-07j -4.61281388e-07-3.27500629e-07j
    3.21317053e-08+1.42540202e-07j  2.89082109e-08-1.40979708e-07j
    7.96548427e-09+4.98924386e-08j  0.00000000e+00+0.00000000e+00j]
  [-2.97919746e-06-2.17256388e-06j  2.91234210e-06+1.15671912e-06j
   -2.39480664e-06+1.11390580e-06j -1.19963624e-06+2.78518655e-07j
   -4.32637762e-07-4.41724154e-07j  5.60680348e-07-7.53309948e-08j
    6.10191151e-08-1.32766047e-07j -1.08757888e-07+9.42479943e-08j
    1.72580816e-09-5.04948119e-08j  0.00000000e+00+0.00000000e+00j]
  [-2.39273436e-06-2.80543645e-06

# Transmitter method

## bit to be transferred

In [6]:
from deepMIMO5 import (

    BinarySource,
    calculate_BER,
)

In [7]:
binary_source = BinarySource()
NUM_STREAMS_PER_TX = eval_transceiver.num_streams_per_tx
k = eval_transceiver.k
b = binary_source(
        [BATCH_SIZE, 1, NUM_STREAMS_PER_TX, k]
    )  # [batch_size, num_tx, num_streams_per_tx, num_databits]

In [8]:
b.shape

(128, 1, 1, 1536)

In [9]:
# Now call the gettransmitSignal method
y, x_rg, x, b, no, h_b, tau_b, h_out = eval_transceiver.gettransmitSignal(
    b=b,  # You can pass your bits here if you have them
    ebno_db=15.0,  # Example Eb/No valueA
    perfect_csi=False,  # Example for perfect CSI
)

# Print the results
print("Received signal (y):", y)
print("Resource grid (x_rg):", x_rg)
print("Transmitted signal (x):", x)
print("Original bits (b):", b)
print("Noise power (no):", no)
print("Channel impulse response (h_b):", h_b)
print("Delay profile (tau_b):", tau_b)
print("Channel response (h_out):", h_out)

h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
Received signal (y): [[[[[-0.05071348+0.03908835j  0.05459997+0.02874602j
      0.02532671+0.07743789j ...  0.03750595+0.13328974j
     -0.05951021+0.02054975j -0.07622566+0.06708716j]
    [ 0.04059523-0.01214933j  0.17665078-0.07006808j
     -0.05969933-0.11890911j ...  0.13570572+0.02134321j
     -0.07801166-0.03572309j  0.03540965+0.09759577j]
    [-0.01815938+0.00769322j  0.02129532-0.02435017j
      0.21332371+0.05755591j ... -0.02001048+0.09608009j
      0.07422321-0.10621965j -0.05218454-0.07448317j]
    ...
    [-0.11792466-0.04530688j  0.03634979-0.01704392j
      0.04503657-0.1109788j  ...  0.07761124+0.03810453j
     -0.12117147-0.01028131j -0.10454205+0.10106961j]
    [ 0.0400743 -0.06907053j -0.0277625 -0.1868638j
     -0.05383131+0.23680784j ... -0.06734365+0.10597465j
     -0.04539353-0.01631433j -0.11221261-0.00743972j]
    [ 0.00414263+0.07778768j  0.0182152 -0.08032204j
      0.1613079 +0.09897985j .

In [10]:
# Print the results
print("Received signal (y):", y.shape)
print("Resource grid (x_rg):", x_rg.shape)
print("Transmitted signal (x):", x.shape)
print("Original bits (b):", b.shape)
print("Noise power (no):", no)
print("Channel impulse response (h_b):", h_b.shape)
print("Delay profile (tau_b):", tau_b.shape)
print("Channel response (h_out):", h_out.shape)

Received signal (y): (128, 1, 1, 14, 76)
Resource grid (x_rg): (128, 1, 1, 14, 76)
Transmitted signal (x): (128, 1, 1, 768)
Original bits (b): (128, 1, 1, 1536)
Noise power (no): 0.015811387
Channel impulse response (h_b): (128, 1, 1, 1, 16, 10, 1)
Delay profile (tau_b): (128, 1, 1, 10)
Channel response (h_out): (128, 1, 1, 1, 16, 1, 76)


## creating dataset for training

In [54]:
# Create a dataset to store b, y, x, tau_b, and h_out
dataset = []

# Number of samples you want to generate
num_samples = 10  # Adjust as needed

for _ in range(num_samples):
    # Generate bits
    binary_source = BinarySource()
    NUM_STREAMS_PER_TX = eval_transceiver.num_streams_per_tx
    k = eval_transceiver.k
    b = binary_source(
        [BATCH_SIZE, 1, NUM_STREAMS_PER_TX, k]
    )  # [batch_size, num_tx, num_streams_per_tx, num_databits]

    # Call the gettransmitSignal method
    y, x_rg, x, b, no, h_b, tau_b, h_out = eval_transceiver.gettransmitSignal(
        b=b,  # Pass the generated bits
        ebno_db=15.0,  # Example Eb/No value
        perfect_csi=False,  # Example for perfect CSI
    )
    print("no",no)
    # Store the generated data in the dataset, including tau_b and h_out
    dataset.append((y, x, b ,no, h_b, tau_b, h_out))
    # y, x_rg, x, b, no, h_b, tau_b, h_out

# Now dataset contains tuples of (b, y, x, tau_b, h_out) for training

h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
no 0.015811387


In [55]:
# Print the dataset
for index, (y, x, b, no, h_b, tau_b, h_out) in enumerate(dataset):
    print(f"Sample {index + 1}:")
    print("Received Signal (y):", y.shape)
    print("Transmitted Signal (x):", x.shape)
    print("Bits (b):", b.shape)
    print("Noise Power (no):", no)  # Assuming no is a float, print its value
    print("Channel Impulse Response (h_b):", h_b.shape)
    print("Delay Profile (tau_b):", tau_b.shape)
    print("Channel Response (h_out):", h_out.shape)
    print("-" * 40)  # Separator for readability

Sample 1:
Received Signal (y): (128, 1, 1, 14, 76)
Transmitted Signal (x): (128, 1, 1, 768)
Bits (b): (128, 1, 1, 1536)
Noise Power (no): 0.015811387
Channel Impulse Response (h_b): (128, 1, 1, 1, 16, 10, 1)
Delay Profile (tau_b): (128, 1, 1, 10)
Channel Response (h_out): (128, 1, 1, 1, 16, 1, 76)
----------------------------------------
Sample 2:
Received Signal (y): (128, 1, 1, 14, 76)
Transmitted Signal (x): (128, 1, 1, 768)
Bits (b): (128, 1, 1, 1536)
Noise Power (no): 0.015811387
Channel Impulse Response (h_b): (128, 1, 1, 1, 16, 10, 1)
Delay Profile (tau_b): (128, 1, 1, 10)
Channel Response (h_out): (128, 1, 1, 1, 16, 1, 76)
----------------------------------------
Sample 3:
Received Signal (y): (128, 1, 1, 14, 76)
Transmitted Signal (x): (128, 1, 1, 768)
Bits (b): (128, 1, 1, 1536)
Noise Power (no): 0.015811387
Channel Impulse Response (h_b): (128, 1, 1, 1, 16, 10, 1)
Delay Profile (tau_b): (128, 1, 1, 10)
Channel Response (h_out): (128, 1, 1, 1, 16, 1, 76)
---------------------

# Baseline Receiver

In [30]:
print(no)
x_hat, no_eff, h_hat, err_var, h_perfect, err_var_perfect = eval_transceiver.channelest_equ(
            y, no, h_b=h_b, tau_b=tau_b, h_out=h_out, perfect_csi=False
        )

# print types
# Print shapes
print("x_hat shape:", x_hat.shape)
print("no_eff shape:", no_eff.shape)
print("h_hat shape:", h_hat.shape)

      
# Print the results
# print("Estimated transmitted signal (x_hat):", x_hat)
print("Effective noise power (no_eff):", no_eff)
print("Estimated channel impulse response (h_hat):", h_hat)
print("Error variance (err_var):", err_var)
print("Perfect channel impulse response (h_perfect):", h_perfect)
print("Error variance for perfect CSI (err_var_perfect):", err_var_perfect)

0.015811387
Num of Pilots: 1
Num of Pilots: 1
h_out after remove nulled shape: (128, 1, 1, 1, 16, 1, 64)
x_hat shape: (128, 1, 1, 768)
no_eff shape: ()
h_hat shape: (128, 1, 1, 1, 1, 14, 64)
Effective noise power (no_eff): 0.038966082
Estimated channel impulse response (h_hat): tf.Tensor(
[[[[[[[-0.6378171 +0.45806658j -0.67213875+0.64399j
       -0.6994911 +0.70043594j ... -0.74688137+0.19874635j
       -0.7094614 +0.15036774j -0.57333106+0.11648221j]
      [-0.6378171 +0.45806658j -0.67213875+0.64399j
       -0.6994911 +0.70043594j ... -0.74688137+0.19874635j
       -0.7094614 +0.15036774j -0.57333106+0.11648221j]
      [-0.6378171 +0.45806658j -0.67213875+0.64399j
       -0.6994911 +0.70043594j ... -0.74688137+0.19874635j
       -0.7094614 +0.15036774j -0.57333106+0.11648221j]
      ...
      [-0.77534467+0.6547066j  -0.6540245 +0.7532288j
       -0.6834081 +0.6118928j  ... -0.62095094+0.0705244j
       -0.65869975+0.18278451j -0.55133766+0.10806336j]
      [-0.77534467+0.6547066j  

In [22]:
b_hat, llr_est = eval_transceiver.demapper_decision(x_hat=x_hat, no_eff=no_eff)
from deepMIMO5 import calculate_BER

BER = calculate_BER(b, b_hat)
print("BER Value:", BER)

BER Value: 0.0022735595703125


# Neural receiver v1 ber high

In [23]:
import numpy as np
import torch
import torch.nn as nn


class NeuralReceiverModel(nn.Module):
    def __init__(self, input_size):
        super(NeuralReceiverModel, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(
            64, 6
        )  # Output for x_hat, no_eff, h_hat, err_var, h_perfect, err_var_perfect

    def forward(self, x):
        x = x.view(x.size(0), -1)  # Flatten the input
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x


class NeuralReceiver:
    def __init__(self, input_size=1064):  # Set the input size to match your data
        self.model = NeuralReceiverModel(input_size)

    def neural_receiver_method(
        self, y, no, h_b=None, tau_b=None, h_out=None, perfect_csi=False
    ):
        # Convert received signal to tensor
        y_tensor = torch.tensor(y, dtype=torch.float32)

        # Perform inference with the neural receiver
        with torch.no_grad():  # Disable gradient calculation for inference
            output = self.model(y_tensor)

        print("output:", output.shape)  # Check the output shape

        # Check if output is a single tensor with 6 elements
        if output.dim() == 1 and output.shape[0] == 6:
            # If the model is returning a single output, handle accordingly
            x_hat = output[:2]  # This will give you the first two elements
            no_eff = output[2].item()  # Assuming the third element is no_eff
        else:
            # Split the output into respective variables
            x_hat = output[0]  # Estimated transmitted signal
            no_eff = output[1]  # Effective noise

            # Convert outputs to numpy arrays for compatibility
            x_hat = x_hat.numpy()  # Convert to numpy array

            # Check if no_eff is a tensor with multiple elements
            if no_eff.dim() > 0 and no_eff.shape[0] > 1:
                no_eff = (
                    no_eff.mean().item()
                )  # Take the mean if it's a tensor with multiple elements
            else:
                no_eff = no_eff.item()  # Convert to float if it's a single value

        # Reshape x_hat to the required shape (128, 2, 2, 768) if applicable
        if x_hat.shape[0] == 6:
            # If x_hat is of shape (6,), we need to determine how to process it
            x_hat = np.zeros(
                (128, 2, 2, 768)
            )  # Create a dummy output with the desired shape
        else:
            # If x_hat is not of the expected shape, handle accordingly
            raise ValueError(f"Unexpected shape for x_hat: {x_hat.shape}")

        return x_hat, no_eff  # Return only x_hat and no_eff

In [24]:
# Instantiate the NeuralReceiver with the correct input size
neural_receiver = NeuralReceiver(input_size=1064)

# Call the neural receiver method with the parameters obtained from gettransmitSignal
# print shapes
print("y shape:", y.shape)
print("no shape:", no.shape)
print("h_b shape:", h_b.shape)
print("tau_b shape:", tau_b.shape)
print("h_out shape:", h_out.shape)

# Instantiate the NeuralReceiver with the correct input size
neural_receiver = NeuralReceiver(input_size=1064)

# Call the neural receiver method with the parameters obtained from gettransmitSignal
x_hat, no_eff = neural_receiver.neural_receiver_method(
    y, no, h_b=h_b, tau_b=tau_b, h_out=h_out, perfect_csi=False
)

# Print the results
print("Estimated transmitted signal (x_hat):", x_hat)
print("Effective noise (no_eff):", no_eff)

y shape: (128, 1, 1, 14, 76)
no shape: ()
h_b shape: (128, 1, 1, 1, 16, 10, 1)
tau_b shape: (128, 1, 1, 10)
h_out shape: (128, 1, 1, 1, 16, 1, 76)
output: torch.Size([128, 6])
Estimated transmitted signal (x_hat): [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 ...


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]]
Effective noise (no_eff): 0.06690168380737305


# Neural receiver v2

In [11]:
import torch
import torch.nn as nn
import numpy as np


class NeuralReceiver(nn.Module):
    def __init__(self):
        """
        Neural Receiver that processes received signals to remove noise and channel effects.
        """
        super(NeuralReceiver, self).__init__()

        # Calculate input dimensions based on y shape (128, 1, 1, 14, 76)
        self.input_features = 14 * 76  # 1064

        # Convolutional layers for feature extraction
        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
        )

        # Calculate the size after convolutions
        self.conv_output_size = 128 * 14 * 76  # Maintaining spatial dimensions

        # Dense layers for signal processing
        self.fc_layers = nn.Sequential(
            nn.Linear(self.conv_output_size, 2048),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(2048, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, 768),  # Output dimension matches required x shape
        )

    def forward(self, y, h_b, tau_b, h_out, no):
        """
        Forward pass of the neural receiver.

        Args:
            y (torch.Tensor): Received signal (128, 1, 1, 14, 76)
            h_b (torch.Tensor): Channel impulse response (128, 1, 1, 1, 16, 10, 1)
            tau_b (torch.Tensor): Delay profile (128, 1, 1, 10)
            h_out (torch.Tensor): Channel response (128, 1, 1, 1, 16, 1, 76)
            no (float): Noise power

        Returns:
            tuple: (x_hat, no_eff)
                - x_hat (torch.Tensor): Processed signal (128, 1, 1, 768)
                - no_eff (float): Effective noise power
        """
        batch_size = y.shape[0]

        # Reshape input for 2D convolution: (batch, channels, height, width)
        y = y.view(batch_size, 1, 14, 76)

        # Apply convolution layers
        x = self.conv_layers(y)

        # Flatten for dense layers
        x = x.view(batch_size, -1)

        # Apply dense layers
        x = self.fc_layers(x)

        # Reshape output to match required dimensions (128, 1, 1, 768)
        x_hat = x.view(batch_size, 1, 1, -1)

        # Calculate effective noise power
        no_eff = self._calculate_effective_noise(x_hat, h_out, no)

        return x_hat, no_eff

    def _calculate_effective_noise(self, x_hat, h_out, no):
        """
        Calculate effective noise power based on the processed signal and channel response.

        Args:
            x_hat (torch.Tensor): Processed signal
            h_out (torch.Tensor): Channel response
            no (float): Original noise power

        Returns:
            float: Effective noise power
        """
        signal_power = torch.mean(torch.abs(x_hat) ** 2)
        channel_effect = torch.mean(torch.abs(h_out) ** 2)
        no_eff = no * signal_power * channel_effect
        return float(no_eff.item())


def numpy_to_torch(arr):
    """Convert numpy array to torch tensor."""
    return torch.from_numpy(arr).float()


def process_signal(y, x, no, h_b, tau_b, h_out):
    """
    Process a signal using the Neural Receiver.

    Args:
        y (numpy.ndarray): Received signal (128, 1, 1, 14, 76)
        x (numpy.ndarray): Transmitted signal (128, 1, 1, 768)
        no (float): Noise power
        h_b (numpy.ndarray): Channel impulse response (128, 1, 1, 1, 16, 10, 1)
        tau_b (numpy.ndarray): Delay profile (128, 1, 1, 10)
        h_out (numpy.ndarray): Channel response (128, 1, 1, 1, 16, 1, 76)

    Returns:
        tuple: (x_hat, no_eff)
            - x_hat (numpy.ndarray): Processed signal (128, 1, 1, 768)
            - no_eff (float): Effective noise power
    """
    # Convert numpy arrays to torch tensors
    y_torch = numpy_to_torch(y)
    h_b_torch = numpy_to_torch(h_b)
    tau_b_torch = numpy_to_torch(tau_b)
    h_out_torch = numpy_to_torch(h_out)

    # Initialize and use the receiver
    receiver = NeuralReceiver()
    x_hat, no_eff = receiver(y_torch, h_b_torch, tau_b_torch, h_out_torch, no)

    # Convert output back to numpy
    x_hat_np = x_hat.detach().numpy()

    return x_hat_np, no_eff

In [12]:
# Example usage
x_hat2, no_eff2 = process_signal(y, x, no, h_b, tau_b, h_out)

C:\Users\HP\AppData\Local\Temp\ipykernel_41504\3815165380.py:101: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Copy.cpp:308.)
  return torch.from_numpy(arr).float()


In [13]:
print(x_hat2.shape)
print(no_eff2)

(128, 1, 1, 768)
5.762677392340265e-05


# Evaluate neural receiver

In [14]:
b_hat2, llr_est = eval_transceiver.demapper_decision(x_hat=x_hat2, no_eff=no_eff2)

In [15]:
from deepMIMO5 import calculate_BER 
BER = calculate_BER(b, b_hat2)
print("BER Value:", BER)

BER Value: 0.5013427734375


In [26]:
# # Add this line to display the figures
# import matplotlib.pyplot as plt

# plt.show()  #

# Plotting the testing of neural receiver,
- Testing on list of enobdb
- Testing on different bits

result:
- without training, It maintains average ber rate of 0.5

In [16]:
# Define the range of Eb/No values
ebno_db_range = range(1, 11)  # Eb/No values from 1 to 10

# Store results
results = []


for ebno_db in ebno_db_range:
    # Generate bits

    # Call the gettransmitSignal method
    y, x_rg, x, b, no, h_b, tau_b, h_out = eval_transceiver.gettransmitSignal(
        b=b,
        ebno_db=ebno_db,  # Current Eb/No value
        perfect_csi=False,
    )

    # Process the received signal using the neural receiver
    # Example usage
    x_hat2, no_eff2 = process_signal(y, x, no, h_b, tau_b, h_out)

    # Calculate Bit Error Rate (BER)
    # Assuming b and x_hat are in the same format, you may need to convert x_hat to bits
    # For simplicity, let's assume x_hat is already in the correct format
    # b_hat = np.round(x_hat)  # Example: rounding to get estimated bits
    # ber = np.mean(b != b_hat)  # Calculate BER

    # # Store the results
    # results.append((ebno_db, ber))
    b_hat2, llr_est = eval_transceiver.demapper_decision(x_hat=x_hat2, no_eff=no_eff2)
    BER = calculate_BER(b, b_hat2)
    results.append((ebno_db, BER))

# Print the results
for ebno_db, ber in results:
    print(f"Eb/No (dB): {ebno_db}, BER: {ber:.4f}")

h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)


d:\Research\AIsensing\deeplearning\AIsim_main2.py:1207: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
Eb/No (dB): 1, BER: 0.5023
Eb/No (dB): 2, BER: 0.5003
Eb/No (dB): 3, BER: 0.5005
Eb/No (dB): 4, BER: 0.5001
Eb/No (dB): 5, BER: 0.5018
Eb/No (dB): 6, BER: 0.5023
Eb/No (dB): 7, BER: 0.5017
Eb/No (dB): 8, BER: 0.5013
Eb/No (dB): 9, BER: 0.4993
Eb/No (dB): 10, BER: 0.5008


In [21]:
# Unzip the results for plotting
ebno_values, ber_values = zip(*results)

import matplotlib.pyplot as plt
# Plotting
# Assuming you have already generated the plot
plt.figure(figsize=(10, 6))
plt.semilogy(ebno_values, ber_values, marker="o", linestyle="-", color="b")
plt.title("BER vs Eb/No")
plt.xlabel("Eb/No (dB)")
plt.ylabel("Bit Error Rate (BER)")
plt.grid(True, which="both", linestyle="--", linewidth=0.5)
plt.xticks(ebno_values)  # Set x-ticks to be the Eb/No values
plt.ylim(1e-6, 1)  # Set y-limits for better visibility
plt.xlim(min(ebno_values), max(ebno_values))

# Define the path where you want to save the PDF
pdf_path = r"D:\Research\AIsensing\deeplearning\data\ber_vs_ebno.pdf"

# Save the plot as a PDF file in the specified directory
plt.savefig(pdf_path, format="pdf")

# Optionally, you can close the plot to free up memory
plt.close()

In [22]:
import os

os.startfile("ber_vs_ebno.pdf")

In [19]:
# Define the number of different bit sequences to test
num_bit_sequences = 5

# Store results
results = []

for i in range(num_bit_sequences):
    # Generate bits
    binary_source = BinarySource()
    NUM_STREAMS_PER_TX = eval_transceiver.num_streams_per_tx
    k = eval_transceiver.k
    b = binary_source(
        [BATCH_SIZE, 1, NUM_STREAMS_PER_TX, k]
    )  # [batch_size, num_tx, num_streams_per_tx, num_databits]

    # Call the gettransmitSignal method
    y, x_rg, x, b, no, h_b, tau_b, h_out = eval_transceiver.gettransmitSignal(
        b=b,
        ebno_db=15.0,  # Use a fixed Eb/No value for testing
        perfect_csi=False,
    )

    # Process the received signal using the neural receiver
    x_hat2, no_eff2 = process_signal(y, x, no, h_b, tau_b, h_out)

    # Calculate Bit Error Rate (BER)
    b_hat2, llr_est = eval_transceiver.demapper_decision(x_hat=x_hat2, no_eff=no_eff2)
    BER = calculate_BER(b, b_hat2)

    # Store the results
    results.append((i + 1, BER))  # Store the sequence number and BER

# Print the results
for seq_num, ber in results:
    print(f"Bit Sequence {seq_num}: BER: {ber:.4f}")

h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
h_freq shape: (128, 1, 1, 1, 16, 1, 76)
y shape: (128, 1, 1, 14, 76)
Bit Sequence 1: BER: 0.5000
Bit Sequence 2: BER: 0.5002
Bit Sequence 3: BER: 0.4995
Bit Sequence 4: BER: 0.5006
Bit Sequence 5: BER: 0.5007


In [ ]:
# bers, blers, BERs = sim_bersingle2(
#     channeldataset="deepmimo",
#     channeltype="ofdm",
#     NUM_BITS_PER_SYMBOL=2,
#     EBN0_DB_MIN=-5.0,
#     EBN0_DB_MAX=25.0,
#     BATCH_SIZE=128,
#     NUM_UT=1,
#     NUM_BS=1,
#     NUM_UT_ANT=1,
#     NUM_BS_ANT=16,
#     showfigure=True,  # or whatever value you want
#     datapathbase="data/",
#     dataset_folder=dataset_folder
# )

# Training phase